config/routes.rb
Hashbros::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  mount Monologue::Engine => '/blog'

  mount API => '/api', :as => 'api'

  devise_for :users

  get 'dashboard' => 'home#dashboard'
  get 'FAQ' => 'home#faq'
  get 'contact' => 'home#contact'
  get 'settings' => 'users#settings'
  get 'leaderboard' => 'home#leaderboard'
  get 'profitability' => 'home#profitability', :as => 'profitability'
  get 'developers' => 'home#developers'
  get 'metrics' => 'home#metrics', :as => 'metrics'

  get '/users/:user_id/rounds' => 'users#rounds'
  get '/users/load_setting/:coin_id' => 'users#load_setting'
  post '/users/update_coin_settings' => 'users#update_coin_settings', :as => 'update_coin_settings'
  post '/users/update_redemption_settings' => 'users#update_redemption_settings', :as => 'update_redemption_settings'
  post '/users/update_auto_trade_settings' => 'users#update_auto_trade_settings', :as => 'update_auto_trade_settings'
  post '/users/settings/edit' => 'users#save_settings', :as => 'edit_user_coin_settings'

  post '/users/dashboard-info' => 'users#get_user_dashboard_info', :as => 'get_user_dashboard_info'
  get '/users/settings/security' => 'users#security', :as => 'user_settings_security'
  get '/users/settings/security/pin' => 'users#edit_pin', :as => 'edit_pin'
  get '/users/settings/security/pin/forgot' => 'users#forgot_pin', :as => 'forgot_pin'
  post '/users/settings/security/pin/reset' => 'users#reset_pin', :as => 'reset_pin'
  get '/users/settings/security/pin/reset/:code' => 'users#reset_pin_form', :as => 'reset_pin_form'
  post '/users/settings/security/pin/set' => 'users#set_pin', :as => 'set_pin'
  post '/users/settings/security/pin/update' => 'users#update_pin', :as => 'update_pin'
  post '/users/settings/security/2fa/check' => 'users#test_2fa', :as => 'test_2fa'
  post '/users/reauthenticate' => 'users#reauthenticate', :as => 'reauthenticate'
  post '/users/load-reauthenticate-modal' => 'users#load_reauthenticate_modal', :as => 'load_reauthenticate_modal'
  get '/users/notifications/mark-all-as-read' => 'notifications#mark_all_as_read'
  get '/notifications' => 'notifications#all', :as => 'all_notifications'
  post '/notifications/poll' => 'notifications#poll', :as => 'notifications_poll'
  get '/users/accept/all-for-beta' => 'users#accept_all_for_beta'

  get 'manage' => 'manage#index'
  get 'manage/deposits' => 'manage#deposits'
  get 'manage/rounds' => 'manage#rounds'
  get 'manage/redemptions' => 'manage#redemptions'
  get 'manage/redemptions/:id/process' => 'manage#process_redemption'
  get 'manage/revenues' => 'manage#revenues'

  get '/users/accept/:id' => 'users#accept_user'

  get '/earnings' => 'users#earnings'
  get '/redemptions' => 'users#redemptions'
  get '/payouts/all' => 'home#payouts'
  post '/payouts/redeem/' => 'users#redeem'

  get '/payouts' => 'users#payouts'
  get '/deposits/all' => 'home#deposits'
  get '/deposits' => 'users#deposits'
  get '/getting-started/' => 'home#getting_started'

  get '/debts/redeem/:id' => 'debts#redeem'

  get '/profitability-analytics' => 'profitability_analytics#index'

  if Rails.env.production?
    get '/404', :to => "errors#error_404"
    post '/404', :to => "errors#error_404"
    get "/422", :to => "errors#error_404"
    post "/422", :to => "errors#error_404"
    get "/500", :to => "errors#error_500"
    post "/500", :to => "errors#error_500"
  end

  resources :users
  resources :rounds
  resources :coins
  resources :pools
  resources :workers
  resources :debts
  resources :withdrawals
  resources :coin_histories

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!,
    :except => [:index, :faq, :contact, :profitability, :metrics]

  # CanCan Permissions
  authorize_resource :class => false, :only => [:test]

  def index
  	# Home page should be dashboard for logged in users
  	if current_user
      if current_user.enabled? or current_user.admin?
  		  return redirect_to action: :dashboard
      end
  	end
  end

  def dashboard
    # Do this to do the joins in just 1 query, not a bunch of others in the view
    @current_user = current_user
  end

  def leaderboard

  end

  def faq

  end

  def contact

  end

  def settings

  end

  def getting_started

  end

  def developers

  end

  def earnings
    @payouts = Payout.find(:all)
    @deposits = Deposit.find(:all)
  end

  def payouts
    @payouts = Payout.find(:all)
  end

  def deposits
    @deposits = Deposit.find(:all)
  end

  # Get coins with their latest coin history and sort by profitability
  def profitability
    @coin_histories = []
    @number_of_days = 7
    # Fix for #101. Will allow us to filter by coins only who are recently updated
    time_cut_off = 15.minutes.ago
    Coin.all.each do |coin|
      if !coin.coin_histories.last.nil? && coin.coin_histories.last.updated_at > time_cut_off
        @coin_histories.push(coin.coin_histories.last)
      end
    end
    @coin_histories.sort_by!(&:btc_per_day).reverse!
  end

  def metrics
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def get_new_users_in_24_hours_count
  return User.find(:all, :conditions => ["created_at between ? and ?",
         DateTime.now - 24.hours, DateTime.now]).count
  end

  def get_all_users_count
    User.count
  end

  def get_active_users_count
  	User.where(:is_enabled => true).count
  end

end

app/views/home/_profitability_table.html.erb
<table class="table table-striped no-margin tablesorter" id="profitability-table">
	<thead>
		<tr>
			<th>Coin</th>
			<th>Profitability</th>
			<th>Difficulty</th>
			<th>Exchange Rate</th>
			<th>Network Hash Rate</th>
		</tr>
	</thead>
	<tbody>
		<% @coin_histories.each do |coin_history| %>
			<% cache coin_history do %>
			<tr data-id="<%= coin_history.coin.id %>">
				<td>
					<span class="pull-left coin-image">
						<%= link_to image_tag(coin_history.coin.image_url, :style => "coin-image-size"), coin_history.coin %>
					</span>
					<%= link_to "#{coin_history.coin.name} (#{coin_history.coin.symbol})", coin_history.coin %><br />
					Blocks : <%= coin_history.blocks %><br />
					Block Reward : <%= "%0.2f" % coin_history.coin.reward %>
					<td>
						<div class="row"><div class="profitability-charts profitability-chart"></div></div>
						<div class="row"><strong>Current Profitability:</strong> <%= "%0.6f" % coin_history.btc_per_day.to_f %></div>
					</td>
					<td>
						<div class="row"><div class="profitability-charts difficulty-chart"></div></div>
						<div class="row"><strong>Current Difficulty:</strong> <%= "%0.2f" % coin_history.diff.to_f %></div>
					</td>
					<td>
						<div class="row"><div class="profitability-charts exchange-chart"></div></div>
						<div class="row"><strong>Current Exchange Rate:</strong> <%= "%0.8f" % coin_history.exchange_rate.to_f %></div>
					</td>
					<td>
					<div class="row"><div class="profitability-charts network-hash-rate-chart"></div></div>
					<div class="row"><strong>Current Network Hash Rate:</strong> <%= coin_history.network_hash_rate_with_magnitude("MHs") %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>
<% cache("profitability charts", :expires_in => 12.hours) do %>
	<%= javascript_tag do %>
		var coin_average_profitabilities = <%= raw Coin.get_average_profitabilities(@number_of_days).to_json %>;
		var coin_average_difficultues = <%= raw Coin.get_average_difficulties(@number_of_days).to_json %>;
		var coin_average_exchanges = <%= raw Coin.get_average_exchanges(@number_of_days).to_json %>;
		var coin_average_network_hash_rates = <%= raw Coin.get_average_network_hash_rates(@number_of_days).to_json %>;
		var number_of_days = <%= @number_of_days %>;
	<% end %>
<% end %>

app/views/home/contact.html.erb
<% title "Contact" %>
<div class="content container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="page-title">Contact Us</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
			<section class="widget">
				<div class="body no-margin">
					<h3><i class="fa fa-envelope"></i> <a href="mailto:bro@hashbros.co.in">bro@hashbros.co.in</a></h3>
					<h3><i class="fa fa-twitter"></i> <a href="https://twitter.com/hashbrospool">@HashBrosPool</a></h3>
					<h3><i class="fa fa-bullhorn"></i> IRC server: irc.freenode.net, channel: #hashbros</h3>
					<h3><i class="fa fa-smile-o"> <a href="http://reddit.com/r/hashbros">/r/HashBros</a></i>
				</div>
			</section>
		</div>
	</div>
</div>

app/views/home/dashboard.html.erb
<% title "Dashboard" %>
<div class="content container">
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-danger">
			  HashBros is shutting down, check out our <%= link_to "statement", "https://hashbros.co.in/blog/2014/hashbros-shutting-down" %> for more details
			</div>
			<h2 class="page-title">Dashboard <small><span class="fa fa-refresh"></span> Auto-refresh in <span id="refresh-countdown">90</span> seconds</small></h2>
		</div>
	</div>
	<div class="row">
		<div class="response col-md-8"></div>
		<div class="col-md-8">
			<section class="widget">
				<div class="body no-margin">
					<% cache "#{current_user.id} metrics", :expires_in => 1.minutes do %>
						<%= render "partials/visits_info" %>
					<% end %>
				</div>
			</section>
			<section class="widget">
				<% cache "#{current_user.id} latest rounds", :expires_in => 1.minutes do %>
					<%= render "partials/user_latest_rounds" %>
				<% end %>
			</section>
		</div>
		<div class="col-md-4">
			<% if !(Engine::ProfitSwitchEngine.current_pool.nil? || Engine::ProfitSwitchEngine.current_coin.nil? || Engine::ProfitSwitchEngine.current_round.nil?) %>
				<% cache "pool stats", :expires_in => 1.minutes do %>
					<%= render 'partials/pool_stats', :current_coin => Engine::ProfitSwitchEngine.current_coin, :current_pool => Engine::ProfitSwitchEngine.current_pool, :current_round => Engine::ProfitSwitchEngine.current_round %>
					<% end %>
			<% end %>
			<%= render "shared/twitter" %>
			<section class="widget">
				<% cache "basic stats", :expires_in => 1.hours do %>
					<%= render "partials/basic_stats" %>
				<% end %>
			</section>
		</div>
	</div>
</div>

app/views/home/deposits.html.erb
<% title "Deposits" %>
<div class="content container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="page-title">All Deposits</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<section class="widget">
				<header>
					<h4>All Deposit History</h4>
				</header>
				<div class="body">
					<% if @deposits.blank? %>
					<p>There are no deposits</p>
					<% else %>
						<%= render "partials/deposit_table", :deposits => @deposits %>
					<% end %>
				</div>
			</section>
		</div>
	</div>
</div>

app/views/home/developers.html.erb
	<% title "Developers" %>
	<div class="content container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="page-title">HashBros Developer API
			</div>
		</div>
		<div class="row">
			<div class="col-md-9">
				<section class="widget">
					<header>
						<h3>
							About
						</h3>
					</header>
					<div class="body">
						<p>As we strive for ultimate transparency it only makes sense to open up the data we already represent on the site in machine readable form, through an API. The following is the documentation for the HashBros API endpoints. As we are in beta these endpoints are subject to change, but we will try and notify our developers of potential changes ahead of time and version our APIs when possible. </p>
					</div>
				</section>
				<section class="widget">
					<header>
						<h3>
							REST API Resources
						</h3>
					</header>	
					<div class="body">
					<!-- Profitability -->
					<header>
						<h3>
							Profitability
						</h3>
					</header>
				        <table class="table table-striped">
				          <thead>
				            <tr>
				              <th><b>Resource</b></th>
				              <th><b>Description</b></th>
				            </tr>
				          </thead>
				          <tbody>
				            <tr>
				              <td><%= link_to "GET /api/profitability", "/api/profitability" %> </td>
				              <td>Returns a sorted list of coin JSON objects in descending order by profitability rating.</td>
				            </tr>
				          </tbody>
				        </table>
				        <!-- Coins -->
				        <header>
						<h3>
							Coins
						</h3>
					</header>
				        <table class="table table-striped">
				          <thead>
				            <tr>
				              <th><b>Resource</b></th>
				              <th><b>Description</b></th>
				            </tr>
				          </thead>
				          <tbody>
				            <tr>
				              <td><%= link_to "GET /api/coins", "/api/coins" %> </td>
				              <td>Returns a sorted list of coin JSON objects in alphabetical order.</td>
				            </tr>
				          </tbody>
				        </table>
				         <!-- Users -->
				        <header>
						<h3>
							Users
						</h3>
					</header>
				        <table class="table table-striped">
				          <thead>
				            <tr>
				              <th><b>Resource</b></th>
				              <th><b>Description</b></th>
				            </tr>
				          </thead>
				          <tbody>
				            <tr>
				              <td><%= link_to "GET /api/users/:id/workers", "/developers" %> </td>
				              <td>Returns a list of worker JSON objects belonging to the user identified by the user id passed.</td>
				            </tr>
				          </tbody>
				        </table>
				          <!-- Workers -->
				        <header>
						<h3>
							Workers
						</h3>
					</header>
				        <table class="table table-striped">
				          <thead>
				            <tr>
				              <th><b>Resource</b></th>
				              <th><b>Description</b></th>
				            </tr>
				          </thead>
				          <tbody>
				            <tr>
				              <td><%= link_to "GET /api/workers/:id", "/developers" %> </td>
				              <td>Returns a worker JSON object identified by the worker id passed.</td>
				            </tr>
				          </tbody>
				        </table>
				      </div>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>

app/views/home/earnings.html.erb
<% title "Earnings" %>
<div class="content container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="page-title">All Earnings</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<section class="widget">
				<header>
					<h4>All Deposit History</h4>
				</header>
				<div class="body">
					<% if @deposits.blank? %>
					<p>There are no deposits</p>
					<% else %>
						<%= render "partials/deposit_table", :deposits => @deposits %>
					<% end %>
				</div>
			</section>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<section class="widget">
				<header>
					<h4>All Payout History</h4>
				</header>
				<div class="body">
					<% if @payouts.blank? %>
					<p>There are no payouts</p>
					<% else %>
						<%= render "partials/payout_table", :payouts => @payouts %>
					<% end %>
				</div>
			</section>
		</div>
	</div>
</div>

app/views/home/faq.html.erb
<% title "FAQ" %>
<div class="content container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="page-title">Frequently Asked Questions</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<section class="widget">
					<div class="body">
						<div class="panel-group" id="accordion2">
							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
										What is HashBros?
									</a>
								</div>
								<div id="collapseOne" class="panel-collapse collapse">
									<div class="panel-body">
										<p><strong>HashBros</strong> is an advanced crypto currency pool mining service. We are a one stop shop for scrypt and alt-coin mining with both profit switching and traditional pools. Our service was built with extreme uptime, reliability, and transparency in mind. Our carefully designed infrastructure places each pool on it's own box, providing a much more modular and scalable pool service than others.</p>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
										What are the fees?
									</a>
								</div>
								<div id="collapseTwo" class="panel-collapse collapse">
									<div class="panel-body">
									   <p>Our fees are much lower than the competing pools out there. For the beta period there will be 1.0% for traditional pools, an additional 0.5% for profit-switching pool plus 0.0005 BTC fee for redemption (transaction fee). Our goal is to continue to <strong>always</strong> have a really low fee for our users even when we launch.</p>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
										What's the current status of HashBros?
									</a>
								</div>
								<div id="collapseFour" class="panel-collapse collapse">
									<div class="panel-body">
										<p>HashBros is in a public beta phase. We had a 3-week long private alpha that allowed us to work on and scale up our engine, so we are opening it up to a public beta.</p>
										<p>In beta, there may still be some rough edges, although the vast majority have been worked out. If you ever encouter a bug, please <%= link_to "contact us", contact_path %> and we'll be sure to work it out.</p>
									</div>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
										What coins will be mined?
									</a>
								</div>
								<div id="collapseFive" class="panel-collapse collapse">
									<div class="panel-body">
										<p>Currently we support: <%= Coin.get_list_of_coins %></p>
										<p>Note that we have a system setup so that we can add and remove crypto currencies, even new ones, on the fly without interruption!</p>
									</div>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseSix">
										How do automatic payouts work?
									</a>
								</div>
								<div id="collapseSix" class="panel-collapse collapse">
									<div class="panel-body">
										<p>Automatic payouts simply cash out your balance on HashBros (deposits) to your personal wallet with the coin of your choice once it breaks the threshold we set. You can manually override our default setting, but we force the automatic payout because of security measures. Note: We currently only payout to BTC wallets</p>
									</div>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseSeven">
										What do you have that others don't?
									</a>
								</div>
								<div id="collapseSeven" class="panel-collapse collapse">
									<div class="panel-body">
										<p>Lots of great things!</p>
										<p>For one, we have a really nice website and we're very open about the operation of the system. Go ahead and ask us a question about it.</p>
										<p>A great profit switching algorithm that isn't based on a 3rd party. We keep track of the various crypto-currency data and make our own profitability choices.</p>
										<p>We're working on a number of really sweet options for users that other pools generally charge extra for or in "donation" fees such as email or possibly SMS alerts when miners go down, as well as any time payouts occur. And not to mention, we're just as open to suggestions as we are questions. If there is enough demand for a particular option, we can add it! Speak up!</p>
									</div>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseEight">
										I have a suggestion for HashBros!
									</a>
								</div>
								<div id="collapseEight" class="panel-collapse collapse">
									<div class="panel-body">
										<p>Please, by all means, we want to hear it! And users should vote on what they want the most. <%= link_to "Give us feedback on UserVoice!", 'https://hashbros.uservoice.com/' %></p>
									</div>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseNine">
										How can I contact HashBros?
									</a>
								</div>
								<div id="collapseNine" class="panel-collapse collapse">
									<div class="panel-body">
										<p>Please visit our <%= link_to 'Contact Us Page', '/contact' %></p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<% meta :title => "HashBros",
     :description => "Crypto Alt Coin Multi Pool Profit Switch",
     :keywords => %w(crypto scrypt alt coin multi pool profit switch bitcoin transparent secure litecoin)
%>
<% if user_signed_in? && !current_user.is_enabled%>
<div class="container flash">
	<div class="alert alert-info alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		Thanks for signing up! You are #<%= current_user.place_in_line %> in the line of users to be enabled
	</div>
</div>
<% end %>
<div class="content container">
		<div class="landing mid">
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="jumbotron">
						<h1>Welcome</h1>
						<p><strong>HashBros</strong> is an advanced crypto currency pool mining service. We are a one stop shop for scrypt and alt-coin mining with both profit switching and traditional pools. Our service was built with extreme uptime, reliability, and transparency in mind. Our carefully designed infrastructure places each pool on it's own box, providing a much more modular and scalable pool service than others.</p>
						<% if not current_user %>
						<p><%= link_to "Join the Beta!", '/users/sign_up', :class => 'btn btn-success btn-lg', :role => 'button' %></p>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="widget widget-white widget-about landing">
		<div class="container">
			<div class="row features">
				<div class="col-sm-4">
					<section class="feature">
						<div class="row">
							<div class="col-xs-4">
								<p>
									<span class="icon background-danger">
										<i class="fa fa-btc"></i>
									</span>
								</p>
							</div>
							<div class="col-xs-8">
								<h4>Mission </h4>
								<p>Our main goals are to help increase the reputability of crypto currencies by providing a robust, secure, and painless pool mining service. </p>
							</div>
						</div>
					</section>
				</div>
				<div class="col-sm-4">
					<section class="feature">
						<div class="row">
							<div class="col-xs-4">
								<p>
									<span class="icon background-warning">
										<i class="fa fa-cogs"></i>
									</span>
								</p>
							</div>
							<div class="col-xs-8">
								<h4>Options</h4>
								<p>When you use HashBros, you have options. We offer a profit switching pool along with many standalone coin pools. You can put your miners on auto pilot or take full control.</p>
							</div>
						</div>
					</section>
				</div>
				<div class="col-sm-4">
					<section class="feature">
						<div class="row">
							<div class="col-xs-4">
								<p>
									<span class="icon background-success">
										<i class="fa fa-search"></i>
									</span>
								</p>
							</div>
							<div class="col-xs-8">
								<h4>Transparency</h4>
								<p>HashBros is dedicated to providing our users with a trustworthy platform. In efforts to do this we give our users maximum transparency. You will know about every round, block, and deposit down to the transfer id. Seriously. </p>
							</div>
						</div>
					</section>
				</div>
			</div>
			<div class="row features">
				<div class="col-sm-4">
					<section class="feature">
						<div class="row">
							<div class="col-xs-4">
								<p>
									<span class="icon background-primary">
										<i class="fa fa-lock"></i>
									</span>
								</p>
							</div>
							<div class="col-xs-8">
								<h4>Secure</h4>
								<p>As victims of pool hackings ourselves, we know how much it hurts to lose precious crypto coins. We've gone the extra mile by writing our own security system to detect malicious behavior. We take security seriously.</p>
							</div>
						</div>
					</section>
				</div>
				<div class="col-sm-4">
					<section class="feature">
						<div class="row">
							<div class="col-xs-4">
								<p>
									<span class="icon background-lime">
										<i class="fa fa-check"></i>
									</span>
								</p>
							</div>
							<div class="col-xs-8">
								<h4>Clean & Easy To Use</h4>
								<p>We pride ourselves in making our website beautiful and effortless to use across all of your devices.</p>
							</div>
						</div>
					</section>
				</div>
				<div class="col-sm-4">
					<section class="feature">
						<div class="row">
							<div class="col-xs-4">
								<p>
									<span class="icon background-info">
										<i class="fa fa-users"></i>
									</span>
								</p>
							</div>
							<div class="col-xs-8">
								<h4>Experience HashBros for yourself!</h4>
								<p>Sign up for the beta now and get hashing in under 2 minutes!</p>
							</div>
						</div>
					</section>
				</div>
			</div>
			<div class="row features text-align-center">
				<div class="col-md-6">
					<h2>Want to know how we stack up?</h2>
					<h4>Detailed <%= link_to "pool metrics", metrics_path %> (BTC/MH, payouts, pool hash rate, active miners etc.)</h4>
					<h4>Free <%= link_to "profitability analytics", profitability_path %> on alt-coins</h4>
				</div>
				<div class="col-md-6">
					<h2>Want more info?</h2>
					<h4>Check out our <%= link_to "frequently asked questions", '/FAQ' %></h4>
					<h4>Feel free to <%= link_to "contact us", "/contact" %></h4>
					<h4>Leave us feature ideas at <%= link_to "UserVoice", "https://hashbros.uservoice.com/" %></h4>
				</div>
			</div>
		</div>
	</div>

app/views/home/leaderboard.html.erb
<% title "Leaderboard" %>
	<div class="content container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="page-title">HashBros Leaderboard</h2>
			</div>
		</div>
		<div class="row">
			<% cache "leaderboard", :expires_in => 10.minutes do %>
				<%= render 'partials/leaderboard_shares' %>
				<%= render 'partials/leaderboard_hash_rate' %>
			<% end %>
		</div>
	</div>
</div>

app/views/home/payouts.html.erb
<% title "Payouts" %>
<div class="content container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="page-title">All Payouts</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<section class="widget">
				<header>
					<h4>All Payout History</h4>
				</header>
				<div class="body">
					<% if @payouts.blank? %>
					<p>There are no payouts</p>
					<% else %>
						<%= render "partials/payout_table", :payouts => @payouts %>
					<% end %>
				</div>
			</section>
		</div>
	</div>
</div>

app/views/home/profitability.html.erb
<% title "Profitability" %>
<% meta :title => "Profitability",
     :description => "Crypto Alt Coin Profitability",
     :keywords => %w(crypto scrypt alt coin profitability exchange difficulty network hash rate)
%>
<div class="content container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="page-title">HashBros Crypto Coin Profitability Index</h2>
			<%= render "partials/ad" %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<section class="widget">
				<div class="body horizontal-scroll-table">
					<%= render "profitability_table"%>
				</div>
			</section>
			<%= render "partials/ad" %>
		</div>
	</div>
</div>